version: 2.1

jobs:   
  hello:
    machine: true     
    steps:  
      - checkout
      - run: echo 'Hello, World'
      - run: cat .circleci/config.yml
    #- run: echo "Hello, FooBar!"
    #  - run: echo "This is message in Circle Worker!"
        #      - run: pwd
        #      - run: uname -a
        #      - run: "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\" Hello, <Nickname>!\"}' https://hooks.slack.com/services/T01FCLYDL02/B01F9JQ7VUM/eme SnzqFNRPtk6ZYLpv7IlpW"
        #- run: "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\" Hello, isong9!\"}' ${SLACK_API_URL}"

workflows:   
  welcome:     
    jobs:       
     - hello
