version: 2.1

jobs:   
  hello:
    machine: true     
    steps:  
      - checkout
      - run: echo 'Hello, World'
      - run: cat .circleci/config.yml

workflows:   
  welcome:     
    jobs:       
     - hello
